In [3]:
from doc2vec import Doc2Vec
import numpy as np

/home/govert/anaconda3/envs/pytorch-par2vec/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


### Load Reuters data

In [22]:
word2id = np.load('data/reuters/reuters_word2id.npy').item(0)
id2word = np.load('data/reuters/reuters_id2word.npy').item(0)
tokenized = np.load('data/reuters/reuters_tokenized.npy')
docs = [[id2word[word_id] for word_id in doc] for doc in tokenized]
x = np.arange(len(tokenized))
# np.random.shuffle(x)
print(x)

[    0     1     2 ..., 20575 20576 20577]


### Init Doc2Vec model

In [5]:
doc2vec = Doc2Vec(vocabulary_size=60000, document_size=21000)

### Fit documents to model

In [ ]:
doc2vec.fit(docs)

Building dictionary
vocab size:  59576
doc size:    20578
Initialized
Average loss at step 0: 307.113861
Average loss at step 2000: 268.504996
Average loss at step 4000: 146.992388
Average loss at step 6000: 107.605375
Average loss at step 8000: 88.790577
Average loss at step 10000: 73.688384
Average loss at step 12000: 65.588068
Average loss at step 14000: 74.132314
Average loss at step 16000: 51.539436
Average loss at step 18000: 49.586868
Average loss at step 20000: 43.187461
Average loss at step 22000: 36.416340
Average loss at step 24000: 31.834820
Average loss at step 26000: 29.502952
Average loss at step 28000: 27.483882
Average loss at step 30000: 27.775099
Average loss at step 32000: 31.767761
Average loss at step 34000: 24.695657
Average loss at step 36000: 25.498940
Average loss at step 38000: 19.577735
Average loss at step 40000: 16.043557
Average loss at step 42000: 14.603270
Average loss at step 44000: 14.145684
Average loss at step 46000: 13.665582
Average loss at step 4

In [40]:
doc_ids, word_ids = doc2vec._build_dictionaries(docs)
batch_data, batch_labels = doc2vec.generate_batch(doc_ids, word_ids,
                                                  doc2vec.batch_size, doc2vec.window_size)


Building dictionary
vocab size:  59576
doc size:    20578


In [41]:
print(len(word_ids))
print(len(doc_ids))

2639090
2639090


In [42]:
for i in batch_data:
    print(i)

[18225  1734     5  1048  7796   102    43   552     0]
[1734    5 1048 7796  102   43  552  387    0]
[   5 1048 7796  102   43  552  387   25    0]
[1048 7796  102   43  552  387   25    9    0]
[7796  102   43  552  387   25    9 1784    0]
[ 102   43  552  387   25    9 1784  113    0]
[  43  552  387   25    9 1784  113    1    0]
[ 552  387   25    9 1784  113    1  640    0]
[ 387   25    9 1784  113    1  640    4    0]
[  25    9 1784  113    1  640    4    9    0]
[   9 1784  113    1  640    4    9 1784    0]
[1784  113    1  640    4    9 1784  113    0]
[ 113    1  640    4    9 1784  113    1    0]
[   1  640    4    9 1784  113    1  640    0]
[ 640    4    9 1784  113    1  640 3449    0]
[   4    9 1784  113    1  640 3449  394    0]
[   9 1784  113    1  640 3449  394    8    0]
[1784  113    1  640 3449  394    8    1    0]
[ 113    1  640 3449  394    8    1  218    0]
[   1  640 3449  394    8    1  218    3    0]
[ 640 3449  394    8    1  218    3  112    0]
[344

In [81]:
a = np.random.randint(40, size=20)
a = np.arange(40)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [117]:
b = np.lib.stride_tricks.as_strided(a, (len(a)-8+1, 8), 2 * a.strides).copy()
print(tokenized[2477])

[10471, 19267, 10470, 33222, 27181, 19212, 29321, 17422, 6794, 21539, 31780, 48887, 45695, 42239, 58981, 48887, 42239, 23590, 48887, 58981, 48887, 49698, 28849, 58981, 37295, 31780, 48887, 42239, 58981, 48887, 42239, 23590, 48887, 49698, 58981, 48887, 49698, 28849, 49698, 58981, 49698, 28828]


In [116]:
for i in tokenized:
    if len(i) > 0 and np.max(i) > 59388:
        print(np.max(i))

59570
59461
59534
59525
59521
59461
59534
59525
59521
59555
59525
59521
59437
59441
59521
59461
59549
59461
59521
59521
59521
59521
59461
59521
59441
59521
59532
59532
59525
59461
59521
59516
59521
59555
59461
59525
59532
59430
59528
59521
59441
59521
59521
59549
59441
59521
59521
59521
59521
59461
59543
59521
59555
59536
59544
59521
59461
59420
59538
59555
59521
59521
59430
59521
59521
59521
59521
59544
59544
59525
59532
59525
59521
59521
59521
59544
59534
59521
59521
59532
59525
59525
59521
59521
59521
59532
59521
59521
59521
59521
59536
59521
59461
59521
59529
59525
59539
59521
59521
59525
59521
59529
59563
59534
59525
59563
59521
59563
59532
59563
59521
59532
59465
59461
59521
59534
59521
59521
59452
59521
59461
59532
59521
59441
59529
59461
59521
59525
59525
59461
59457
59521
59529
59521
59570
59521
59521
59571
59544
59529
59557
59529
59529
59521
59461
59525
59525
59532
59529
59557
59521
59461
59461
59457
59525
59536
59525
59539
59461
59521
59534
59529
59461
59521
59521
59525
5952

59525
59529
59529
59422
59444
59521
59521
59521
59399
59563
59534
59457
59502
59529
59561
59532
59456
59571
59521
59532
59521
59532
59521
59507
59521
59534
59570
59532
59461
59532
59532
59461
59570
59521
59457
59521
59521
59461
59521
59424
59521
59521
59532
59521
59521
59525
59521
59566
59539
59521
59525
59532
59521
59525
59521
59525
59521
59532
59544
59521
59521
59525
59521
59525
59521
59529
59457
59532
59461
59461
59521
59525
59461
59521
59521
59521
59525
59539
59405
59521
59529
59532
59534
59430
59521
59521
59521
59525
59525
59532
59521
59521
59439
59521
59521
59521
59532
59461
59525
59521
59525
59521
59461
59538
59521
59521
59521
59521
59461
59525
59461
59461
59534
59525
59532
59521
59521
59532
59532
59457
59525
59532
59525
59521
59521
59521
59532
59457
59563
59534
59532
59461
59534
59532
59521
59525
59525
59532
59521
59461
59525
59525
59461
59525
59534
59525
59461
59571
59538
59525
59521
59521
59521
59521
59521
59536
59441
59521
59521
59536
59461
59461
59461
59521
59461
59457
5952

59521
59461
59461
59521
59461
59536
59521
59521
59521
59525
59422
59525
59525
59521
59524
59521
59417
59430
59525
59430
59521
59525
59534
59555
59461
59525
59521
59461
59461
59525
59525
59521
59529
59534
59529
59529
59555
59457
59521
59521
59525
59536
59521
59529
59525
59525
59521
59521
59525
59424
59532
59525
59529
59536
59566
59521
59521
59536
59539
59521
59521
59424
59461
59461
59534
59557
59461
59461
59532
59542
59529
59461
59538
59521
59529
59521
59525
59544
59529
59566
59532
59532
59532
59521
59521
59525
59532
59525
59525
59532
59461
59521
59532
59529
59420
59532
59539
59525
59461
59444
59521
59521
59516
59521
59534
59529
59399
59521
59420
59521
59461
59521
59525
59521
59461
59521
59525
59524
59521
59425
59521
59430
59542
59461
59461
59521
59532
59461
59532
59521
59521
59525
59494
59532
59461
59525
59532
59536
59521
59461
59430
59461
59525
59461
59521
59539
59521
59457
59461
59420
59525
59521
59521
59521
59525
59521
59521
59441
59538
59521
59425
59532
59525
59525
59534
59461
5952

59461
59461
59532
59420
59521
59521
59461
59521
59420
59420
59461
59521
59521
59521
59534
59532
59536
59538
59463
59457
59457
59420
59525
59461
59521
59461
59521
59461
59430
59532
59525
59521
59532
59430
59461
59424
59461
59544
59534
59544
59461
59525
59461
59534
59532
59532
59534
59461
59424
59557
59521
59532
59557
59529
59529
59521
59542
59521
59521
59521
59457
59532
59529
59430
59521
59521
59525
59525
59521
59544
59544
59529
59529
59525
59461
59521
59532
59521
59521
59525
59521
59532
59521
59521
59521
59532
59521
59521
59521
59521
59521
59521
59521
59521
59461
59461
59521
59521
59521
59430
59525
59532
59521
59521
59525
59461
59529
59525
59534
59532
59461
59536
59461
59536
59461
59521
59461
59521
59521
59521
59525
59521
59461
59521
59441
59461
59534
59534
59457
59461
59420
59420
59461
59399
59521
59461
59461
59532
59525
59521
59525
59521
59521
59521
59521
59521
59521
59521
59532
59525
59461
59521
59406
59461
59529
59529
59521
59525
59525
59525
59525
59461
59525
59532
59525
59571
5940

In [84]:
b[3,3] = 9999

In [85]:
np.random.shuffle(b)

In [119]:
id2word[28828]

'Reuter'

In [ ]:
import tensorflow as tf


a = tf.random_uniform([10, 10], -1.0, 1.0)
a = tf.reshape(a, [-1])
printtf.tile(a, [1, 10])